// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GerenciamentoTarefas.Domain.Enums;
using System;
using System.Collections.Generic;

namespace GerenciamentoTarefas.Domain.Entidades;

public partial class Tarefa
{
    public Tarefa(string titulo, string descricao)
    {
        Titulo = titulo;
        Descricao = descricao;
        Status = StatusTarefa.Pendente;
        DataCriacao = DateTime.Now;
    }

    public int Id { get; set; }
    public string Titulo { get; set; }
    public string Descricao { get; set; }
    public DateTime DataCriacao { get; set; }
    public DateTime? DataConclusao { get; set; }
    public StatusTarefa Status { get; set; }

    public void AtualizarTarefa(string titulo, string descricao, StatusTarefa status)
    {
        Titulo = titulo;
        Descricao = descricao;
        if (Status == StatusTarefa.Concluida && status != StatusTarefa.Concluida)
        {
            DataConclusao = null;
        }

        Status = status;
    }

}